In [352]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import json

In [353]:
amzn = pd.read_csv("Final CSV's/amzn_final.csv", usecols = [1, 2])
appl = pd.read_csv("Final CSV's/appl_final.csv", usecols = [1, 2])
bitcoin = pd.read_csv("Final CSV's/bitcoin_final.csv", usecols = [1, 2])
cpi = pd.read_csv("Final CSV's/cpi_final.csv", usecols = [1, 2])
dow = pd.read_csv("Final CSV's/Dow_Jones_Composite_final.csv", usecols = [1, 2])
eth = pd.read_csv("Final CSV's/eth_final.csv", usecols = [1, 2])
googl = pd.read_csv("Final CSV's/googl_final.csv", usecols = [1, 2])
solana = pd.read_csv("Final CSV's/solana_final.csv", usecols = [1, 2])
msft = pd.read_csv("Final CSV's/msft_final.csv", usecols = [1, 2])
spcomp = pd.read_csv("Final CSV's/spcomp_final.csv", usecols = [1, 2])
nasdaq = pd.read_csv("Final CSV's/NASDAQ_Composite_final.csv", usecols = [1, 2])
gold = pd.read_csv("Final CSV's/spgold_final.csv", usecols = [1, 2])
nvda = pd.read_csv("Final CSV's/nvda_final.csv", usecols = [1, 2])
tsla = pd.read_csv("Final CSV's/tsla_final.csv", usecols = [1, 2])
oil = pd.read_csv("Final CSV's/oil_final.csv", usecols = [1, 2])
xmag = pd.read_csv("Final CSV's/xmag_final.csv", usecols = [1, 2])
silver = pd.read_csv("Final CSV's/silver_final.csv", usecols = [1, 2])

amzn2 = pd.read_csv("Final CSV's/amzn_final.csv", usecols = [1, 3])
appl2 = pd.read_csv("Final CSV's/appl_final.csv", usecols = [1, 3])
bitcoin2 = pd.read_csv("Final CSV's/bitcoin_final.csv", usecols = [1, 3])
cpi2 = pd.read_csv("Final CSV's/cpi_final.csv", usecols = [1, 3])
dow2 = pd.read_csv("Final CSV's/Dow_Jones_Composite_final.csv", usecols = [1, 3])
eth2 = pd.read_csv("Final CSV's/eth_final.csv", usecols = [1, 3])
googl2 = pd.read_csv("Final CSV's/googl_final.csv", usecols = [1, 3])
solana2 = pd.read_csv("Final CSV's/solana_final.csv", usecols = [1, 3])
msft2 = pd.read_csv("Final CSV's/msft_final.csv", usecols = [1, 3])
spcomp2 = pd.read_csv("Final CSV's/spcomp_final.csv", usecols = [1, 3])
nasdaq2 = pd.read_csv("Final CSV's/NASDAQ_Composite_final.csv", usecols = [1, 3])
gold2 = pd.read_csv("Final CSV's/spgold_final.csv", usecols = [1, 3])
nvda2 = pd.read_csv("Final CSV's/nvda_final.csv", usecols = [1, 3])
tsla2 = pd.read_csv("Final CSV's/tsla_final.csv", usecols = [1, 3])
oil2 = pd.read_csv("Final CSV's/oil_final.csv", usecols = [1, 3])
xmag2 = pd.read_csv("Final CSV's/xmag_final.csv", usecols = [1, 3])
silver2 = pd.read_csv("Final CSV's/silver_final.csv", usecols = [1, 3])

In [354]:
data = pd.merge(amzn, appl, how = "outer", on = "Date")
data = pd.merge(data, bitcoin, how = "outer", on = "Date")
data = pd.merge(data, dow, how = "outer", on = "Date")
data = pd.merge(data, eth, how = "outer", on = "Date")
data = pd.merge(data, googl, how = "outer", on = "Date")
data = pd.merge(data, solana, how = "outer", on = "Date")
data = pd.merge(data, msft, how = "outer", on = "Date")
data = pd.merge(data, spcomp, how = "outer", on = "Date")
data = pd.merge(data, nasdaq, how = "outer", on = "Date")
data = pd.merge(data, gold, how = "outer", on = "Date")
data = pd.merge(data, nvda, how = "outer", on = "Date")
data = pd.merge(data, tsla, how = "outer", on = "Date")
data = pd.merge(data, oil, how = "outer", on = "Date")
data = pd.merge(data, xmag, how = "outer", on = "Date")
data = pd.merge(data, silver, how = "outer", on = "Date")
data

,Date,AMZN Price,APPL Price,Bitcoin Price,Dow Jones Composite Price,Ethereum Price,META Price,Solana Price,MSFT Price,S&P 500 Composite Price,NASDAQ Composite Price,S&P Gold Price,NVDA Price,TSLA Price,Oil Futures Price,XMAG Price,Silver Price
0,01-01-2011,NaN,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01-01-2012,NaN,NaN,5.2677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-01-2013,NaN,NaN,13.3041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-01-2014,NaN,NaN,771.4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-01-2015,NaN,NaN,314.1360,NaN,0.690215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12382,12-31-2022,NaN,NaN,16538.3479,NaN,NaN,NaN,9.870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12383,12-31-2023,NaN,NaN,42224.0900,NaN,2281.870000,NaN,101.720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12384,12-31-2024,219.39,250.42,93631.3000,42544.22,3346.340000,585.51,189.610,421.50,5881.63,19310.79,1537.61,134.29,403.84,74.58,19.62,28.940001
12385,12-31-2025,230.82,271.86,87559.9000,48063.29,2975.240000,660.09,124.875,483.62,6845.50,23241.99,2527.42,186.50,449.72,61.35,22.57,71.139999
12386,12-31-2025,230.82,271.86,87559.9000,48063.29,2975.240000,660.09,124.875,483.62,6845.50,23241.99,2527.42,186.50,449.72,61.35,22.57,70.603000

In [355]:
data["Date"] = pd.to_datetime(data["Date"], format = "%m-%d-%Y")
data = data.sort_values(by = "Date")
data = data.reset_index(drop = True)
data = data.set_index("Date", drop = True)
data

,AMZN Price,APPL Price,Bitcoin Price,Dow Jones Composite Price,Ethereum Price,META Price,Solana Price,MSFT Price,S&P 500 Composite Price,NASDAQ Composite Price,S&P Gold Price,NVDA Price,TSLA Price,Oil Futures Price,XMAG Price,Silver Price
Date,,,,,,,,,,,,,,,,
1987-05-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.63,NaN,NaN
1987-05-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.45,NaN,NaN
1987-05-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.55,NaN,NaN
1987-05-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.60,NaN,NaN
1987-05-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.63,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-06,212.79,258.86,68747.8,46669.88,2107.81,573.02,NaN,372.88,6611.83,21996.34,NaN,177.64,352.82,NaN,22.5047,72.847
2026-04-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.5000,NaN
2026-04-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0421,NaN
2026-04-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.1250,NaN
2026-04-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.9731,NaN

In [356]:
data_range = data.loc["2016-12-31" : "2025-12-31"]
data_range

,AMZN Price,APPL Price,Bitcoin Price,Dow Jones Composite Price,Ethereum Price,META Price,Solana Price,MSFT Price,S&P 500 Composite Price,NASDAQ Composite Price,S&P Gold Price,NVDA Price,TSLA Price,Oil Futures Price,XMAG Price,Silver Price
Date,,,,,,,,,,,,,,,,
2016-12-31,NaN,NaN,963.599,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-01,NaN,NaN,997.777,NaN,10.732100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-02,NaN,NaN,1021.790,NaN,8.370000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-03,37.6835,29.0375,1044.080,19881.76,292.463013,116.86,NaN,62.58,2257.83,5429.08,676.53,2.5503,14.4660,55.05,NaN,16.356001
2017-01-04,37.8590,29.0050,1153.540,19942.16,300.468994,118.69,NaN,62.30,2270.75,5477.00,678.45,2.6098,15.1327,54.57,NaN,16.499001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-29,232.0700,273.7600,87323.600,48461.93,2949.410000,658.69,123.950,487.10,6905.74,23474.35,2528.88,188.2200,459.6400,63.10,22.7525,70.460000
2025-12-30,232.5300,273.0800,88382.900,48367.06,2973.280000,665.95,125.597,487.48,6896.24,23419.08,2553.74,187.5400,454.4300,62.30,22.6700,77.374001
2025-12-30,232.5300,273.0800,88382.900,48367.06,2973.280000,665.95,125.597,487.48,6896.24,23419.08,2553.74,187.5400,454.4300,62.30,22.6700,77.919000
2025-12-31,230.8200,271.8600,87559.900,48063.29,2975.240000,660.09,124.875,483.62,6845.50,23241.99,2527.42,186.5000,449.7200,61.35,22.5700,71.139999
2025-12-31,230.8200,271.8600,87559.900,48063.29,2975.240000,660.09,124.875,483.62,6845.50,23241.99,2527.42,186.5000,449.7200,61.35,22.5700,70.603000

In [357]:
data_solana = data.loc["2020-08-11" : "2025-12-31"]
data_solana

,AMZN Price,APPL Price,Bitcoin Price,Dow Jones Composite Price,Ethereum Price,META Price,Solana Price,MSFT Price,S&P 500 Composite Price,NASDAQ Composite Price,S&P Gold Price,NVDA Price,TSLA Price,Oil Futures Price,XMAG Price,Silver Price
Date,,,,,,,,,,,,,,,,
2020-08-11,154.0335,109.3750,11395.405816,27686.91,379.01,256.13,3.2985,203.38,3333.69,10782.82,1133.15,10.8500,91.6260,43.68,NaN,26.037001
2020-08-12,158.1120,113.0100,11576.814267,27976.84,387.12,259.89,3.7558,209.19,3380.35,11012.24,1134.72,11.4403,103.6507,45.09,NaN,25.955000
2020-08-13,158.0510,115.0100,11763.009141,27896.72,424.31,261.30,3.7300,208.70,3373.43,11042.50,1147.18,11.4430,108.0667,44.87,NaN,27.694000
2020-08-14,157.4010,114.9075,11742.876374,27931.02,438.11,261.24,3.4099,208.90,3372.85,11019.30,1135.19,11.5640,110.0474,44.86,NaN,26.065001
2020-08-15,NaN,NaN,11865.383053,NaN,432.32,NaN,3.1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-29,232.0700,273.7600,87323.600000,48461.93,2949.41,658.69,123.9500,487.10,6905.74,23474.35,2528.88,188.2200,459.6400,63.10,22.7525,70.460000
2025-12-30,232.5300,273.0800,88382.900000,48367.06,2973.28,665.95,125.5970,487.48,6896.24,23419.08,2553.74,187.5400,454.4300,62.30,22.6700,77.374001
2025-12-30,232.5300,273.0800,88382.900000,48367.06,2973.28,665.95,125.5970,487.48,6896.24,23419.08,2553.74,187.5400,454.4300,62.30,22.6700,77.919000
2025-12-31,230.8200,271.8600,87559.900000,48063.29,2975.24,660.09,124.8750,483.62,6845.50,23241.99,2527.42,186.5000,449.7200,61.35,22.5700,71.139999
2025-12-31,230.8200,271.8600,87559.900000,48063.29,2975.24,660.09,124.8750,483.62,6845.50,23241.99,2527.42,186.5000,449.7200,61.35,22.5700,70.603000

In [358]:
data_xmag = data.loc["2024-10-22" : "2025-12-31"]
data_xmag

,AMZN Price,APPL Price,Bitcoin Price,Dow Jones Composite Price,Ethereum Price,META Price,Solana Price,MSFT Price,S&P 500 Composite Price,NASDAQ Composite Price,S&P Gold Price,NVDA Price,TSLA Price,Oil Futures Price,XMAG Price,Silver Price
Date,,,,,,,,,,,,,,,,
2024-10-22,189.70,235.86,67342.3,42924.89,2624.24,582.01,167.359,427.51,5851.20,18573.13,1606.78,143.59,217.97,75.59,20.0000,34.831001
2024-10-23,184.71,230.76,67266.7,42514.95,2548.98,563.69,174.952,424.60,5797.42,18276.65,1589.08,139.56,213.65,74.68,19.8758,33.639999
2024-10-24,186.38,230.57,68017.3,42374.36,2524.05,567.78,174.586,424.73,5809.86,18415.49,1600.43,140.41,260.48,74.27,19.8300,33.611000
2024-10-25,187.83,231.41,66884.2,42114.40,2453.46,573.25,165.414,428.15,5808.12,18518.61,1603.75,141.54,269.19,75.62,19.7700,33.603001
2024-10-26,NaN,NaN,67032.2,NaN,2475.56,NaN,172.657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-29,232.07,273.76,87323.6,48461.93,2949.41,658.69,123.950,487.10,6905.74,23474.35,2528.88,188.22,459.64,63.10,22.7525,70.460000
2025-12-30,232.53,273.08,88382.9,48367.06,2973.28,665.95,125.597,487.48,6896.24,23419.08,2553.74,187.54,454.43,62.30,22.6700,77.374001
2025-12-30,232.53,273.08,88382.9,48367.06,2973.28,665.95,125.597,487.48,6896.24,23419.08,2553.74,187.54,454.43,62.30,22.6700,77.919000
2025-12-31,230.82,271.86,87559.9,48063.29,2975.24,660.09,124.875,483.62,6845.50,23241.99,2527.42,186.50,449.72,61.35,22.5700,71.139999
2025-12-31,230.82,271.86,87559.9,48063.29,2975.24,660.09,124.875,483.62,6845.50,23241.99,2527.42,186.50,449.72,61.35,22.5700,70.603000

In [359]:
data2 = pd.merge(amzn2, appl2, how = "outer", on = "Date")
data2 = pd.merge(data2, bitcoin2, how = "outer", on = "Date")
data2 = pd.merge(data2, dow2, how = "outer", on = "Date")
data2 = pd.merge(data2, eth2, how = "outer", on = "Date")
data2 = pd.merge(data2, googl2, how = "outer", on = "Date")
data2 = pd.merge(data2, solana2, how = "outer", on = "Date")
data2 = pd.merge(data2, msft2, how = "outer", on = "Date")
data2 = pd.merge(data2, spcomp2, how = "outer", on = "Date")
data2 = pd.merge(data2, nasdaq2, how = "outer", on = "Date")
data2 = pd.merge(data2, gold2, how = "outer", on = "Date")
data2 = pd.merge(data2, nvda2, how = "outer", on = "Date")
data2 = pd.merge(data2, tsla2, how = "outer", on = "Date")
data2 = pd.merge(data2, oil2, how = "outer", on = "Date")
data2 = pd.merge(data2, xmag2, how = "outer", on = "Date")
data2 = pd.merge(data2, silver2, how = "outer", on = "Date")
data2

,Date,AMZN Percent Change Rate,APPL Percent Change Rate,Bitcoin Percent Change Rate,DOW Percent Change Rate,Ethereum Percent Change Rate,META Percent Change Rate,Solana Percent Change Rate,MSFT Percent Change Rate,S&P 500 Composite Percent Change Rate,NASDAQ Composite Percent Change Rate,S&P Gold Percent Change Rate,NVDA Percent Change Rate,TSLA Percent Change Rate,Oil Percent Change Rate,XMAG Percent Change Rate,Silver Percent Change Rate
0,01-01-2011,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01-01-2012,NaN,NaN,111.556544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01-01-2013,NaN,NaN,98.475944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-01-2014,NaN,NaN,102.306335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-01-2015,NaN,NaN,98.172715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12382,12-31-2022,NaN,NaN,99.606089,NaN,100.000000,NaN,102.047146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12383,12-31-2023,NaN,NaN,100.059812,NaN,99.571930,NaN,99.823356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12384,12-31-2024,99.136918,99.294211,101.323145,99.930685,100.300331,99.030850,100.594196,99.216157,99.571521,99.096875,100.874511,97.672558,96.749000,100.457974,99.695122,99.429670
12385,12-31-2025,99.264611,99.553244,99.068824,99.371949,100.065920,99.120054,99.425146,99.208173,99.264237,99.243822,98.969355,99.445452,98.963537,98.475120,99.558888,91.943029
12386,12-31-2025,99.264611,99.553244,99.068824,99.371949,100.065920,99.120054,99.425146,99.208173,99.264237,99.243822,98.969355,99.445452,98.963537,98.475120,99.558888,90.610762

In [360]:
data2["Date"] = pd.to_datetime(data2["Date"], format = "%m-%d-%Y")
data2 = data2.sort_values(by = "Date")
data2 = data2.reset_index(drop = True)
data2 = data2.set_index("Date")
data2

,AMZN Percent Change Rate,APPL Percent Change Rate,Bitcoin Percent Change Rate,DOW Percent Change Rate,Ethereum Percent Change Rate,META Percent Change Rate,Solana Percent Change Rate,MSFT Percent Change Rate,S&P 500 Composite Percent Change Rate,NASDAQ Composite Percent Change Rate,S&P Gold Percent Change Rate,NVDA Percent Change Rate,TSLA Percent Change Rate,Oil Percent Change Rate,XMAG Percent Change Rate,Silver Percent Change Rate
Date,,,,,,,,,,,,,,,,
1987-05-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-05-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.033816,NaN,NaN
1987-05-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.542005,NaN,NaN
1987-05-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.269542,NaN,NaN
1987-05-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.161290,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-06,101.439672,101.148796,99.509457,100.355255,99.03726,99.74933,NaN,99.844696,100.442676,100.535486,NaN,100.140932,97.845198,NaN,100.479971,99.894411
2026-04-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.979115,NaN
2026-04-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.409333,NaN
2026-04-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.359776,NaN
2026-04-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.343135,NaN

In [361]:
data2_range = data2.loc["2016-12-31" : "2025-12-31"]
data2_solana = data2.loc["2020-08-11" : "2025-12-31"]
data2_xmag = data2.loc["2024-10-22" : "2025-12-31"]

In [363]:
#data.to_csv("Asset Price Data.csv")
#data2.to_csv("Asset Percent Change Data.csv")
#data_range.to_csv("Visualization Analysis Full Price.csv")
#data_solana.to_csv("Visualization Analysis Solana Price.csv")
#data_xmag.to_csv("Visualization Analysis XMAG Price.csv")
#data2_range.to_csv("Visualization Analysis Full Percent.csv")
#data2_solana.to_csv("Visualization Analysis Solana Percent.csv")
#data2_xmag.to_csv("Visualization Analysis XMAG Percent.csv")